name: Build and Sign Windows Installer

on:
  push:
    branches:
      - release

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '22'
        distribution: 'temurin'

    - name: Extract Version from Windows Script
      id: extract_version_windows
      run: |
        @echo off
        setlocal enabledelayedexpansion
        REM Find the line containing --app-version and extract the version number
        for /f "tokens=2 delims=^" %%a in ('findstr /c:"--app-version" installer\create_windows_installer.bat') do (
            set "line=%%a"
            for /f "tokens=2 delims=^" %%b in ("!line!") do (
                set "version=%%b"
            )
        )
        REM Remove the quotes from the version number
        set version=%version:"=%
        REM Output the version number
        echo Version: %version%
        echo "VERSION=$version" >> $GITHUB_ENV
        endlocal


    - name: Build Windows Installer
      run: |
        cd installer
        ./create_windows_installer.bat

    - id: upload_windows
      name: Upload Windows Installer
      uses: actions/upload-artifact@v4
      with:
        name: windows-installer
        path: installer/Nortantis-${{ env.VERSION }}.msi
    
    - name: Submit Signing Request for Windows Installer
      id: sign_windows
      uses: signpath/github-action-submit-signing-request@v1
      with:
        api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
        organization-id: 'cb1b9ef5-2e6a-442f-acb7-8521004476b5'
        project-slug: 'nortantis'
        signing-policy-slug: 'test-signing'
        github-artifact-id: '${{steps.upload_windows.outputs.artifact-id}}'
        wait-for-completion: true
        output-artifact-directory: './installer/signed'

    - name: Upload Signed Windows Installer
      uses: actions/upload-artifact@v4
      with:
        name: signed-windows-installer
        path: ./installer/signed/Nortantis-${{ env.VERSION }}.msi




